apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  selector:
    app: backend
    tier: backend
  ports:
    - port: 3000
      targetPort: 3000
  externalIPs:
    - "192.168.43.90"