apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
    tier: database
spec:
  selector:
    app: database
    tier: database
  ports:
    - port: 27017
      targetPort: 27017
  externalIPs:
    - 192.168.43.90