apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
    tier: database
spec:
  selector:
    matchLabels:
      app: database
      tier: database
  template:
    metadata:
      name: database
      labels:
        app: database
        tier: database
    spec:
      containers:
        - name: database
          image: mongo:4.0.5-xenial
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: database
              mountPath: /data/db
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: database
          emptyDir: {}